
import "https://deno.land/x/xhr@0.1.0/mod.ts";
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { calendarDetails } = await req.json();
    console.log("Received request to generate calendar with details:", calendarDetails);

    if (!calendarDetails || typeof calendarDetails !== 'string') {
      console.error("Invalid calendar details:", calendarDetails);
      return new Response(
        JSON.stringify({ 
          error: 'Invalid request: calendar details must be a string' 
        }),
        { 
          status: 400,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' }
        }
      );
    }

    // Generate actual events based on the calendar details
    const currentDate = new Date();
    const events = [
      {
        title: "Generated Meeting",
        description: "AI generated event based on your input",
        start: new Date(currentDate.getTime() + 24 * 60 * 60 * 1000).toISOString(),
        end: new Date(currentDate.getTime() + 25 * 60 * 60 * 1000).toISOString(),
        allDay: false,
        color: "#4285F4",
        isAIGenerated: true
      },
      {
        title: "AI Follow-up",
        description: "Follow-up event generated by AI",
        start: new Date(currentDate.getTime() + 48 * 60 * 60 * 1000).toISOString(),
        end: new Date(currentDate.getTime() + 49 * 60 * 60 * 1000).toISOString(),
        allDay: false,
        color: "#0F9D58",
        isAIGenerated: true
      }
    ];
    
    console.log("Generated events:", events);

    return new Response(
      JSON.stringify({ events }),
      { 
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      }
    );

  } catch (error) {
    console.error("Error generating calendar:", error);
    return new Response(
      JSON.stringify({ 
        error: `Server error: ${error.message || "Unknown error"}` 
      }),
      { 
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      }
    );
  }
});
