// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nyzqzfbsszsenmhvazoh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55enF6ZmJzc3pzZW5taHZhem9oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NzUwODcsImV4cCI6MjA2MTI1MTA4N30.xXRpJFjCyoME1L6jjM7zC12tODonHKQz3vIfWQG-wKI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);